### ISSUE TITLE
Do we need such a huge .gitignore?

### ISSUE THREAD

**Issue by raehik** [readingschool-cs-club/JayI#2]
Just took a look at the `.gitignore` we've got, and it seems pretty big. My guess is that not all of those lines need to be present, at least not for now. I'm guessing Saleem made a template one and used it here or something: do you think we can cut it down a bit?

**Comment by ghost** [comment]
how do u use git

**Comment by ghost** [comment]
I'm doing it on my terminal on fedora

**Comment by ghost** [comment]
I have git installed according to saleem

**Comment by ed-bristow** [comment]
I think Ben said he was going to do a thing on it next Monday.

**Comment by ghost** [comment]
I guess but i cant wait till then

**Comment by ghost** [comment]
the thing on cloud9 is not refreshing properly either

**Comment by ghost** [comment]
its showing the old one

**Comment by ed-bristow** [comment]
Why can't you wait?

**Comment by ghost** [comment]
because im trying to edit jayi from my terminal

**Comment by ed-bristow** [comment]
Edit it from GitHub then. You don't have to use the terminal!

**Comment by ghost** [comment]
but its good practice

**Comment by ed-bristow** [comment]
You can't practise something you don't know.

**Comment by raehik** [comment]
Yeah, I'll go over ways to use Git & GitHub and how I use it next Monday. It'll take me a while to get stuff together. Meanwhile, this is a decent representation of my Git workflow:
![git-workflow.tty.gif](https://cloud.githubusercontent.com/assets/3764592/6449771/1c40b472-c11b-11e4-9cc2-aa070aef1036.gif)

**Comment by ghost** [comment]
thanks ben i don't get some bits of it like the git s and cm but i'll try and figure it out. I'm guessing ur thing updates the file

**Comment by ed-bristow** [comment]
I think I've done a bit of something in a terminal on Linux to start a minecraft server and edit Python documents on an iMac.

**Comment by raehik** [comment]
Hold on, short tutorial coming, just taking me some time to write

**Comment by raehik** [comment]
Haha, that gif was fun to do. I'm gonna use a bunch of gifs to explain CLI things since they're fun to make and use.

In a few sentences, this is what you need to do:
1. Make changes to files. (I assume you know how to do this, can be in/out of terminal)
2. `git add [file...]` e.g. `git add README.md JayI.py` -- this **stages** the files which sort of 'preps' them for committing. It means you can edit lots and lots of files and only commit a few (the ones that you `git add`).
3. `git commit` -- this'll first ask you for a commit message if you don't specify `-m "msg"` as well. It'll open in your default editor. I usually just do `git commit -m "bla bla bla"`.
4. `git push` -- push whatever commits you just made to the remote repo, which is this place on GitHub.

Note that if you get errors about merging, you'll have to do some `git pull`ing and possibly manual merging, which means removing lines you don't want.

**Comment by raehik** [comment]
`git s` and `cm` are aliases for commands I use (incredibly) often. They translate to `git status` and `git commit -m` respectively.

**Comment by ghost** [comment]
oh that makes sense thanks but the final problem i have is that how do i find my github stuff on my comp if im using fedora or the commands wont do anything

**Comment by ghost** [comment]
i have git installed btw

**Comment by raehik** [comment]
You have to `git clone` the repo to get a copy on your local machine. Check the [front repo page](https://github.com/readingschool-cs-club/JayI), it has a box for 'HTTPS clone URL'. So you need to run:

```
git clone 'https://github.com/readingschool-cs-club/JayI.git'
```

**Comment by ghost** [comment]
oh wow that worked thanks

**Comment by ghost** [comment]
how did u make that gif i wanna make one ! :P

**Comment by ghost** [comment]
of my terminal that looks much worse than yours !

**Comment by ghost** [comment]
yours is a zshell i think

**Comment by raehik** [comment]
Yeah, I use zsh. You can find all my config files for everything I use at [raehik/dotfiles](/raehik/dotfiles).

**Comment by ghost** [comment]
saleem said ur dot files silently destroy ur computer ! i have no clue what to do with the dot files any way !! :D

**Comment by raehik** [comment]
Gif was made with an old script which calls some programs I had to build manually, I think `ttyrec` and `ttygif`.

**Comment by raehik** [comment]
And my dotfiles don't "silently destroy" anything! They just overwrite any previous files you had with the same names :)

**Comment by ghost** [comment]
this is meant to be an issue thing but it has turned into like a chat site !

**Comment by raehik** [comment]
whoops, yeah. Collaboration is kinda a learning process for me too, so who cares :D

**Comment by ghost** [comment]
anyways its good we should make an issue called general where we can just post any problems we have or we can just use this one

**Comment by raehik** [comment]
That sounds like a good idea. I'll make one now.

**Comment by raehik** [comment]
Hold on, this was never actually answered! See original question (kinda waiting for Saleem's reply).

**Comment by ghost** [comment]
Oh right sorry

**Comment by saleemrashid1** [comment]
Yes we do

**Comment by raehik** [comment]
why plz? :(

**Comment by saleemrashid1** [comment]
Cos.

**Comment by raehik** [comment]
no really, why? We espec. don't need the `Distribution / packaging` section.
