### ISSUE TITLE
General Git, GitHub or unrelated questions/problems!

### ISSUE THREAD

**Issue by raehik** [readingschool-cs-club/JayI#3]
This is intended to be a place for anyone to ask random questions about Git, command-line tools, or any problems you might be having. We might find a more appropriate place to keep this stuff later, but for now GitHub gives us an easy solution with Issues. Ask away!

**Comment by ghost** [comment]
Hi!

**Comment by ghost** [comment]
Yessss I finally managed to edit in on my terminal
Yayyyyy

**Comment by ghost** [comment]
That gif was very helpful thanks !

**Comment by raehik** [comment]
Hah, cool, no problem :)

**Comment by ghost** [comment]
Oh, just a question what does 'git push' do ? I tried reading git push --help but it doesn't really help !

**Comment by raehik** [comment]
Basically, the repo you get when you do `git clone` is kind of separate from the one here. It's a 'local copy' of the repo, and you can make whatever changes you like locally. However, to get them on this repo, the 'remote repo', you have to do a `git push` to push all the commits you made to here.

Simply, when it says 'Updates remote refs using local refs' it means 'add the commits the remote repository is missing'. Of course if someone _else_ has committed before you and you try to push your changes where you say "commit 1 has parent 1234567890abcdef", Git will know something's up because that commit already has a child. So then you'll have a conflict and you have to do some merging, and things get more complicated from there.

By 'parent' and 'child' I mean relationships, as in:

```
parent --> child
```

**Comment by ghost** [comment]
Yeah, I think I sort of get that ! Don't get the parent child stuff but I get the main idea of how the commands work. Thanks !

**Comment by raehik** [comment]
(why'd you close this, Saleem?)

**Comment by saleemrashid1** [comment]
Cos it bad.

**Comment by raehik** [comment]
bad how? What other way do you suggest we do this? Easy & obvious way of asking for help.
