### ISSUE TITLE
file access needs rewrite

### ISSUE THREAD

**Issue by ghost** [readingschool-cs-club/JayI#4]
File access needs rewrite so escaping etc. can be added

**Comment by raehik** [comment]
Probably best thing to do here would be to store it in a CSV. Easy reading/writing for machines & humans, likely some module for Python to help writing & escaping (only quotes really need to be escaped, though)

**Comment by saleemrashid1** [comment]
I'm gonna fix it!!!

**Comment by saleemrashid1** [comment]
Not quotes, comma's need escaping!!!

**Comment by saleemrashid1** [comment]
In this case, colons!!!!

**Comment by raehik** [comment]
Commas don't need escaping. Enclose each column in quotes and you've escaped almost every character already.
I think a CSV file would be better than having colons between fields. More standardised.

**Comment by saleemrashid1** [comment]
Should have entire modular rewrite (see [issue4](../tree/issue4))
