### ISSUE TITLE
don't put responses.txt in the git repository

### ISSUE THREAD

**Issue by ghost** [readingschool-cs-club/JayI#5]
Stop adding it!

**Comment by raehik** [comment]
But we might want to package JayI with some starting knowledge. Also, it might be useful to use it in branches so that other people can immediately do the same tests you're doing.

For now though, agreed that we should keep it out of master.

**Comment by ghost** [comment]
But it still starts off with knowledge! And if we did it like you say then if you did `rm responses.txt` which seems like a useless data file to get back to factory settings you might be screwed. Until you work it out.
