### ISSUE TITLE
Can't get this working on pycharm HELP

### ISSUE THREAD

**Issue by ghost** [readingschool-cs-club/JayI#6]
Hi, I have installed pycharm on my fedora but when I tried to run JayI.py it returned this error:

Traceback (most recent call last):
  File "/home/Shreyas/Github/JayI/JayI.py", line 98, in <module>
    Jay.respond()
  File "/home/Shreyas/Github/JayI/JayI.py", line 61, in respond
    trigger = input()
  File "<string>", line 1, in <module>
NameError: name 'Hello' is not defined

Process finished with exit code 1

can someone help. It ran perfectly when I just type in python JayI.py

**Comment by ghost** [comment]
Don't worry fixed it found that the python version was set to 2.7 so i set it to 3.4.2

**Comment by saleemrashid1** [comment]
Have you set up the git plugin
