### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by ghost** [readingschool-cs-club/JayI#8]

**Comment by saleemrashid1** [comment]
@the-twee STOP SPAMMING THE DAMN ISSUES! USE AN EMAIL!

---

`hub`: shrs.pndt@gmail.com

**Comment by raehik** [comment]
Saleem, if you continue to mess around with the repo like this (locking issues, disabling the issues feature, reverting commits) I'll take you off this repo's owners list. The JayI repo isn't your GitHub plaything, so stop abusing your repo privileges. I'm reopening this until I'm happy that something is resolved.

**Comment by the-twee** [comment]
its alright ben its working now

**Comment by the-twee** [comment]
the only problem is all of my commits have been put by muhammeds name

**Comment by the-twee** [comment]
and my name is off the contributers list

**Comment by raehik** [comment]
It's working because I reenabled issues, otherwise you wouldn't be able to comment here :/

**Comment by raehik** [comment]
Huh, that's strange

**Comment by the-twee** [comment]
however if you do "git log" as said by Saleem you see my name

**Comment by raehik** [comment]
Did you or Ed change your emails or something? That's how GitHub maps commitors -> GitHub users.

**Comment by the-twee** [comment]
No

**Comment by the-twee** [comment]
Well i dont know about ed but i didnt

**Comment by the-twee** [comment]
and when i said it worked i meant the editing of jayi.py

**Comment by raehik** [comment]
Oh, and it was Muhammed that replaced your commits. Checking log now

**Comment by the-twee** [comment]
do u mean "git log"
git log says the same thing it says the commit i did "The trigger needs to be lowered not the response"
on my name but when you go on the actual repo it says i have made no commits and all the commits ive made it says muhammed's made them

**Comment by raehik** [comment]
Hmm. On my fresh copy I've got "Author: coderbeard <melbeik02@gmail.com>" for that commit. Bit worrying. Could you copy that whole directory and save it somewhere else as a backup? In case we need to revert to that. Hopefully Saleem hasn't been messing around with rewriting history, because that messes things up *big* time.

**Comment by the-twee** [comment]
So should I copy all the files(JayI.py, README.md) to my computer or something

**Comment by raehik** [comment]
Wherever your local copy is, `$ cp -R JayI JayI-bak` or something. I mean the local copy, since we might be dealing with rewritten history.

**Comment by saleemrashid1** [comment]
What? All I did was remove him from the organisation temporarily 'cause he's ****ing me off. I have "coderbeard" in my local one but "the-twee" in my Cloud9 one. I can try rewriting it back

**Comment by saleemrashid1** [comment]
I don't mess about with history!

**Comment by raehik** [comment]
Uhh, that's really not cool. Please don't remove people from the org.

**Comment by raehik** [comment]
You didn't touch the history, though?

**Comment by saleemrashid1** [comment]
Nope. HE IS REALLY ANNOYING ME. WAS GONNA PUT BACK TOMORROW MORNING. LOOK AT THE ISSUES ON PYCHAT!

**Comment by saleemrashid1** [comment]
It DOESN'T rewrite history by removing people

**Comment by saleemrashid1** [comment]
damn, mine is 29 commits back!

**Comment by raehik** [comment]
That is no reason to remove someone from the organisation. If you're being annoyed, **unsubscribe from issue emails!**

**Comment by saleemrashid1** [comment]
he is spamming the issues!!! you can't unsubscribe from JUST issues.

**Comment by the-twee** [comment]
ben when you look at the issues from pychat look at ur email at the photo saleem sent you'll find out why i was annoyed

**Comment by the-twee** [comment]
he was messing around with my profile despite me telling him not to

**Comment by saleemrashid1** [comment]
@the-twee YOU HAVE AN EMAIL ACCOUNT. USE IT!!!

---

`hub`: shrs.pndt@gmail.com

**Comment by saleemrashid1** [comment]
damn, my command line tool keeps backfiring!

**Comment by saleemrashid1** [comment]
for browsing github

**Comment by saleemrashid1** [comment]
anyway, i only revert certain commits

**Comment by the-twee** [comment]
anyways ive accepted ur invitation ben, but it still says the same thing

**Comment by saleemrashid1** [comment]
anyway, rewriting history doesn't let you change author? does it?

**Comment by raehik** [comment]
FFS, Saleem you've been removed from the Owners team so this **** doesn't happen for a while. Some hints for things you should NOT DO again if you want to be added back:
  * SAY when you might mess things up before applying changes.
  * Don't screw with people's computers.
  * Stop being such an idiot. Pranks are fun, screwing things up isn't.
I'm tired and I'm going to bed. I'll review whatever happened today later. I shan't respond any more today (and I'm busy tomorrow evening too).

**Comment by raehik** [comment]
the-twee, I added you back to the JayI team as well. Things should be back to normal, apart fomr commits maybe.

**Comment by saleemrashid1** [comment]
I didn't screw with anything. I've not rewritten history at all in this organisation. Applying what changes?

**Comment by saleemrashid1** [comment]
Everyone unf**ked.
