### ISSUE TITLE
We need to reset the repo

### ISSUE THREAD

**Issue by raehik** [readingschool-cs-club/JayI#9]
Yesterday after some troubles, the-twee got removed from the organisation and things started happening to the repo. All of the-twee's commits were changed to someone else's and now it seems that every commit in the history has been duplicated.

Rather than fiddle around with rewriting history (I'd prefer not), Amartya and I feel that it'd be best to reset the repo. All of the previous history will be wiped, so we'll start fresh **with the current repo state**. That means all your commits will be lost, but none of the current work. That'll include the wiki (which we should be able to keep all history of, by the way).

If anyone has another idea or wants to voice their opinion/question, please **email** me or Amartya rather than comment on this issue. Saleem complained about the volume of issue emails and he had a point, so I'm looking into other ways to talk about normal things -- probably [Gitter](https://gitter.im/), basically a chatroom for GitHub. We'll figure things out on Monday. We **won't** be deleting anything until CS club next week!

If we start anew, we'll keep this old repo but change its name and prevent anyone writing to it (i.e. committing any more).

**Comment by saleemrashid1** [comment]
Fixed.

**Comment by saleemrashid1** [comment]
**EVERYONE DELETE YOUR GIT REPO AND WORKSPACE AND DO IT ALL AGAIN!!!**

**Comment by saleemrashid1** [comment]
I looked at @the-twee's push and rebased from that. Then cherry-picked the ones after. Fixed.

**Comment by raehik** [comment]
OK, thanks!

**Comment by saleemrashid1** [comment]
Anyway, keep backups of the repo, in case @SirEdBr or @coderbeard don't read this, push and mess up the history

**Comment by the-twee** [comment]
I have a backup

**Comment by saleemrashid1** [comment]
But your backup is useless (i.e. you can't use it effectively)

**Comment by raehik** [comment]
!!! What's with you rewriting history left right and centre? I really dislike it.

**Comment by raehik** [comment]
ALWAYS ask someone if you're going to blank something **they wrote**! I'm pretty pissed off about this.

**Comment by spudowiar** [comment]
This isn't rewriting history, this is cleaning up

**Comment by spudowiar** [comment]
Well, sorry :(

**Comment by Zephyr12** [comment]
<a href="https://imgflip.com/i/jguzq"><img src="https://i.imgflip.com/jguzq.jpg" title="made at imgflip.com"/></a>

**Comment by spudowiar** [comment]
I've seen that one

**Comment by spudowiar** [comment]
WTF is a sad face on here???

**Comment by spudowiar** [comment]
:) :D

**Comment by spudowiar** [comment]
You made it an hour ago?

**Comment by raehik** [comment]
Oh, how did you un-edit things? I looked, but couldn't find a way to do it (main reason why I was kinda angry)

**Comment by spudowiar** [comment]
Because I always keep backups

**Comment by spudowiar** [comment]
I may not ask to delete stuff but I never **permanently** delete **anything**

**Comment by raehik** [comment]
Ok, that's reassuring. Sorry I got pretty mad. Maybe I should backup stuff like that too (usually I only do big things). How do you do it?

**Comment by spudowiar** [comment]
I took a backup of the repository, the pull requests, issues and wiki

**Comment by spudowiar** [comment]
I used the GitHub API

**Comment by raehik** [comment]
Thanks, didn't know about that.
